name: Add repository secrets
 
on:
  workflow_dispatch:
    inputs:
        repo:
          type: string
          description: 'The name of the repo to add the secrets to'
          required: true
        maven_secrets:
          type: boolean
          description: 'If the repo should be given NeoForged Maven publishing keys'
          required: false
          default: true
        sonatype_secrets:
          type: boolean
          description: 'If the repo should be given Sonatype (Maven Central) publishing keys'
          required: false
          default: false
        gpp_secrets:
          type: boolean
          description: 'If the repo should be given Gradle Plugin Portal publishing keys'
          required: false
          default: false
        gpg_private_key:
          type: boolean
          description: 'If the repo should be given access to the GPG private key and the password. Most projects published to maven should sign the artifacts produced'
          required: false
          default: true

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.x'
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 376723
          private_key: ${{ secrets.APPLICATION_KEY }}
          repository: neoforged/${{ github.event.inputs.repo }}
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Add secrets
        run: groovy .github/workflows/scripts/add_secrets.groovy
        env:
          AUTH_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
          REPO_NAME: neoforged/${{ github.event.inputs.repo }}
          EVENT_PATH: ${{ github.event_path }}